name: "Development CI"

on:
  push:
    branches:
      - main

jobs:
  docker-image-build-publish:
    name: Build docker image and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Get current version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .

    

      - name: Build docker image
        run: docker build -t ghcr.io/rohed-appnap/my-docker-image:${{ steps.get-version.outputs.version }} .

      - name: Push docker image
        run: docker push ghcr.io/rohed-appnap/my-docker-image:${{ steps.get-version.outputs.version }}


        - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/dashboard:${{ steps.get-version.outputs.version }}
        env:
          DOCKER_BUILDKIT: 1
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}