# name: "Development CI"

# on:
#   push:
#     branches:
#       - main

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

# jobs:
#   docker-image-build-publish:
#     name: Build docker image and push to docker hub
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Login to Docker hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}


#       - name: Get current version
#         id: get-version
#         run: |
#           VERSION=$(jq -r '.version' package.json)
#           echo "::set-output name=version::$VERSION"
#         shell: bash
#         working-directory: ${{ github.workspace }}


#       - name: Build and push Docker image
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.Docker_REGISTRY }}
#         run: |
#           docker build -t ghcr.io/rohed-appnap/pipeline-demo/rohed85-my-app:${{ github.sha }} .
#           echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
#           docker push ghcr.io/rohed-appnap/pipeline-demo/rohed85-my-app:${{ github.sha }}