
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v3

      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - run: npm i -g npm@9.5.1
      - run: node -v
      - run: npm -v
      - run: export NVM_DIR=~/.nvm
      - run: source ~/.nvm/nvm.sh
      - run: npm install
      - run: npm run build

      - name: Login to Docker Hub
        if: ${{ success() }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Get current date 
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"


      - name: Build docker image
        if: ${{ success() }}
        run: docker build . --file Dockerfile --tag rohed85/my-app:${{ steps.date.outputs.date }}
      

      - name: Push docker image
        if: ${{ success() }}
        run: docker push rohed85/my-app:${{ steps.date.outputs.date }}


        - name: Develop Build Status
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://amrpet.com/favicon.png
          SLACK_MESSAGE: Develop Build Failed
          SLACK_TITLE: AmarPet Frontend Develop Build Status
          SLACK_USERNAME: AmarPet Frontend Dev Server
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      
