
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v3

      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - run: npm i -g npm@9.5.1
      - run: node -v
      - run: npm -v
      - run: export NVM_DIR=~/.nvm
      - run: source ~/.nvm/nvm.sh
      - run: npm install
      - run: npm run build

      - name: Login to Docker Hub
        if: ${{ success() }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}


      - name: Build docker image
        run: docker build . --file Dockerfile --tag amarpet:v1.x rohed85/my-app
      
      - name: Push docker image
        run: docker push rohed85/my-app
      
