
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]

env:
  IMAGE_TAG: v1.x


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v3

      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - run: npm i -g npm@9.5.1
      - run: node -v
      - run: npm -v
      - run: export NVM_DIR=~/.nvm
      - run: source ~/.nvm/nvm.sh
      - run: npm install
      - run: npm run build

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin


      - name: Get current date 
        id: date
        run: echo "::set-output name=date::$(date +'v1.'+%m')"


      - name: Build docker image
        run: docker build . --file Dockerfile --tag rohed85/my-app:v1.x

      
      - name: Push docker image
        run: docker push rohed85/my-app:v1.x


  
      
