name: "Development CI"

on:
  push:
    branches:
      - main

jobs:
  docker-image-build-publish:
    name: Build docker image and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Get current version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .

      - name: Log in to the github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PASS_TOKEN }}

      - name: Build docker image
        run: docker build -t ghcr.io/rohed-appnap/my-docker-image:${{ steps.get-version.outputs.version }} .

      - name: Push docker image
        run: docker push ghcr.io/rohed-appnap/my-docker-image:${{ steps.get-version.outputs.version }}